# For more information: https://laravel.com/docs/sail
version: '3'
services:
    nginx:
        image: 'nginx:latest'
        ports:
            - '${HTTP_PORT:-8000}:80'
            - '${SSL_PORT:-443}:443'
        environment:
            - SSL_PORT=${SSL_PORT:-443}
            - APP_SERVICE=${APP_SERVICE:-laravel.test}
            - SERVER_NAME=${SERVER_NAME:-localhost}
            - SSL_DOMAIN=${SSL_DOMAIN:-localhost}
            - SSL_ALT_NAME=${SSL_ALT_NAME:-DNS:localhost}
        volumes:
            - './docker/nginx/certs:/etc/nginx/certs'
            - './docker/nginx/templates:/etc/nginx/templates'
        depends_on:
            - ${APP_SERVICE:-laravel.test}
        networks:
            - sail
    laravel.test:
        build:
            context: ./docker/php/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - postgres
            - postgres_test
            - redis
            - rabbitmq
    postgres:
        image: postgres:14.0
        container_name: ${APP_NAME}_postgres
        restart: unless-stopped
        tty: true
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./docker/databases/${DB_DATABASE}:/var/lib/postgresql/data
        networks:
            - sail
    postgres_test:
        image: postgres:14.0
        container_name: ${APP_NAME}_postgres_test
        restart: unless-stopped
        ports:
            - "${FORWARD_DB_PORT_TEST:-5433}:5432"
        environment:
            POSTGRES_DB: ${DB_TESTING_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./docker/databases/${DB_TESTING_DATABASE}:/var/lib/postgresql/data
        networks:
            - sail
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    rabbitmq:
        image: rabbitmq:3.10.7-management
        hostname: rabbitmq
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=rmuser
            - RABBITMQ_DEFAULT_PASS=rmpassword
        volumes:
            - ./docker/rabbitmq:/var/lib/rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-nginx:
        driver: local
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
