name: Tests
on:
  pull_request:
    branches: [master]
jobs:
  test-build:
    name: Build and test application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure PHP 8.2
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
          extensions: mbstring, dom, fileinfo, mysql, libxml, xml, xmlwriter, dom, tokenizer, filter, json, phar, pcre, openssl, pdo, intl, curl

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Clear Config
        run: php artisan config:clear

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Compile CSS and Javascript
        run: |
          npm install
          npm run build
#          cat public/mix-manifest.json # See asset versions in log

      - name: Static analysis via PHPStan
        run: composer analyse

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          APP_ENV: testing
          CACHE_DRIVER: array
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          MAIL_MAILER: array
          QUEUE_CONNECTION: sync
          SESSION_DRIVER: array
          TELESCOPE_ENABLED: false
        run: ./vendor/bin/phpunit
